apiVersion: v2
name: grafascope-scrapers
description: Grafascope scrapers chart (vmagent + victoria-logs-collector)
type: application
version: 0.1.0

dependencies:
  - name: vmagent
    version: 0.1.0
    repository: "file://../../scrapers/vmagent"
    condition: vmagent.enabled

  - name: victoria-logs-collector
    version: 0.2.7
    repository: "file://../../scrapers/victoria-logs-collector"
    condition: victoria-logs-collector.enabled
