apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-service-a
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: service-a
    {{- include "demo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.serviceA.port }}
      targetPort: http
