{{- $ctx := dict "helm" . }}
{{- $useGlobal := and .Values.global .Values.global.gfsUser .Values.global.gfsUser.username }}
{{- if and (.Values.serviceAccount.create | default true) (not $useGlobal) }}
{{- $saName := .Values.serviceAccount.name }}
{{- if and .Values.global .Values.global.gfsUser .Values.global.gfsUser.username }}
{{- $saName = .Values.global.gfsUser.username }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "vm.fullname" $ctx) $saName }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
