{{- $ctx := dict "helm" . }}
{{- if (.Values.serviceAccount.create | default true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "vm.fullname" $ctx) .Values.serviceAccount.name }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
